import esbuild from 'esbuild';
import process from 'process';
import module from 'module';
import { sassPlugin } from 'esbuild-sass-plugin';
import fs from 'fs';
import path from 'path';

const builtins = module.builtinModules;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
This plugin is built by Yazan Ammar (github.com/YazanAmmar).
*/
`;

const prod = process.argv[2] === 'production';

const vaultDir =
  'C:\\Users\\user\\Desktop\\obsidian\\MyVault\\.obsidian\\plugins\\obsidian-theme-engine';

function copyToVault() {
  if (!fs.existsSync(vaultDir)) {
    fs.mkdirSync(vaultDir, { recursive: true });
  }
  fs.copyFileSync('main.js', path.join(vaultDir, 'main.js'));
  fs.copyFileSync('styles.css', path.join(vaultDir, 'styles.css'));
  fs.copyFileSync('manifest.json', path.join(vaultDir, 'manifest.json'));
  console.log('[+] Build finished and copied to Obsidian Vault!');
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: {
    main: 'src/main.ts',
    styles: 'src/styles/main.scss',
  },
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/closebrackets',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/comment',
    '@codemirror/fold',
    '@codemirror/gutter',
    '@codemirror/highlight',
    '@codemirror/history',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/matchbrackets',
    '@codemirror/panel',
    '@codemirror/rangeset',
    '@codemirror/rectangular-selection',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/stream-parser',
    '@codemirror/text',
    '@codemirror/tooltip',
    '@codemirror/view',
    ...builtins,
  ],
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  minify: prod,
  treeShaking: true,
  outdir: '.',
  plugins: [
    sassPlugin(),
    {
      name: 'obsidian-workflow',
      setup(build) {
        build.onEnd((result) => {
          if (result.errors.length === 0) {
            if (!prod) {
              copyToVault();
            }
          }
        });
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  console.log('[+] Production build completed.');
  process.exit(0);
} else {
  await context.watch();
  console.log('[+] Watching for changes... (Press Ctrl+C to stop)');
}
