import { PluginSettings } from './types';
export const DEFAULT_VARS = {
  'Plugin Integrations': {
    '--iconize-icon-color': '#00aaff',
  },
  Backgrounds: {
    '--background-primary': '#1e1e1e',
    '--background-primary-alt': '#252525',
    '--background-secondary': '#2a2a2a',
    '--background-secondary-alt': '#303030',
    '--background-modifier-border': '#444444',
    '--background-modifier-border-hover': '#555555',
    '--background-modifier-border-focus': '#007acc',
    '--background-modifier-flair': '#3a3a3a',
    '--background-modifier-hover': '#3a3a3a',
    '--background-modifier-active': '#4a4a4a',
  },
  Text: {
    '--text-normal': '#e0e0e0',
    '--text-muted': '#999999',
    '--text-faint': '#666666',
    '--text-on-accent': '#ffffff',
    '--text-accent': '#00aaff',
    '--text-accent-hover': '#33bbff',
    '--text-selection': '#007acc66',
    '--h1-color': '#e0e0e0',
    '--h2-color': '#d0d0d0',
    '--h3-color': '#c0c0c0',
    '--h4-color': '#b0b0b0',
    '--h5-color': '#a0a0a0',
    '--h6-color': '#909090',
  },
  Navigation: {
    '--nav-item-color': '#999999',
    '--nav-item-color-hover': '#e0e0e0',
    '--nav-item-color-active': '#e0e0e0',
    '--nav-item-background-hover': '#3a3a3a',
    '--nav-item-background-active': '#3a3a3a',
  },
  Links: {
    '--link-color': '#00aaff',
    '--link-color-hover': '#33bbff',
    '--link-external-color': '#00aaff',
    '--link-external-color-hover': '#33bbff',
    '--link-unresolved-color': '#00aaff',
  },
  Editor: {
    '--caret-color': '#e0e0e0',
    '--code-comment': '#666666',
    '--code-function': '#e0de71',
    '--code-keyword': '#fa99cd',
    '--code-operator': '#fb464c',
    '--code-property': '#53dfdd',
    '--code-string': '#44cf6e',
  },
  Markdown: {
    '--hr-color': '#444444',
    '--blockquote-border-color': '#007acc',
    '--blockquote-color': '#d0d0d0',
    '--blockquote-bg': 'transparent',
    '--tag-color': '#33bbff',
    '--tag-color-hover': '#33bbff',
    '--tag-bg': '#1e1e1e',
    '--checklist-done-color': '#33bbff',
    '--code-normal': '#e0e0e0',
    '--code-background': '#2d2d2d',
    '--text-highlight-bg': '#2c6887',
    // Tables
    '--table-background': 'transparent',
    '--table-border-color': '#444444',
    '--table-header-background': 'transparent',
    '--table-row-alt-background': 'transparent',
    // Callouts (RGB triplet variables)
    '--callout-default': '2, 122, 255',
    '--callout-info': '2, 122, 255',
    '--callout-warning': '233, 151, 63',
    '--callout-error': '251, 70, 76',
    '--callout-success': '68, 207, 110',
    '--callout-tip': '83, 223, 221',
    '--callout-question': '233, 151, 63',
    '--callout-important': '83, 223, 221',
    '--callout-bug': '251, 70, 76',
    '--callout-example': '168, 130, 255',
    '--callout-quote': '158, 158, 158',
    '--callout-todo': '2, 122, 255',
    '--callout-summary': '83, 223, 221',
    '--callout-fail': '251, 70, 76',
  },
  Notices: {
    '--cm-notice-text-default': '#e0e0e0',
    '--cm-notice-bg-default': '#2a2a2a',
  },
  'Interactive Elements': {
    '--interactive-normal': '#5a5a5a',
    '--interactive-hover': '#6a6a6a',
    '--interactive-accent': '#007acc',
    '--interactive-accent-hover': '#3399dd',
    '--interactive-success': '#28a745',
    '--interactive-error': '#dc3545',
    '--interactive-warning': '#ffc107',
  },
  'UI Elements': {
    '--titlebar-background': '#252525',
    '--titlebar-background-focused': '#303030',
    '--titlebar-text-color': '#e0e0e0',
    '--sidebar-background': '#252525',
    '--sidebar-border-color': '#333333',
    '--header-background': '#2a2a2a',
    '--header-border-color': '#333333',
    '--vault-name-color': '#e0e0e0',
    '--tab-background-active': '#1e1e1e',
    '--tab-text-color': '#666666',
    '--tab-text-color-active': '#999999',
    '--workspace-background-translucent': '#00000099',
  },
  'Graph View': {
    '--graph-line': '#444444',
    '--graph-node': '#999999',
    '--graph-text': '#e0e0e0',
    '--graph-node-unresolved': '#dc3545',
    '--graph-node-focused': '#ffffff',
    '--graph-node-tag': '#86efac',
    '--graph-node-attachment': '#60a5fa',
  },
  Canvas: {
    '--canvas-background': '#1e1e1e',
    '--canvas-card-label-color': '#666666',
    '--canvas-dot-pattern': '#363636',
  },
  Misc: {
    '--scrollbar-thumb-bg': '#444444',
    '--scrollbar-active-thumb-bg': '#ffffff33',
    '--scrollbar-bg': '#2a2a2a',
    '--divider-color': '#444444',
  },
};

export const DEFAULT_PROFILE = {
  vars: {},
  themeType: 'auto',
  snippets: [],
  convertImagesToJpg: false,
  jpgQuality: 85,
};

const OLED_MATRIX_PROFILE = {
  vars: {
    '--iconize-icon-color': '#00ff00',
    '--background-primary': '#000000',
    '--background-primary-alt': '#0a0a0a',
    '--background-secondary': '#050505',
    '--background-secondary-alt': '#101010',
    '--background-modifier-border': '#223322',
    '--background-modifier-border-hover': '#44ff44',
    '--background-modifier-border-focus': '#00ff00',
    '--background-modifier-flair': '#111111',
    '--background-modifier-hover': '#1a1a1a',
    '--background-modifier-active': '#002a00',
    '--text-normal': '#f0f0f0',
    '--text-muted': '#666666',
    '--text-faint': '#444444',
    '--text-on-accent': '#000000',
    '--text-accent': '#00ff00',
    '--text-accent-hover': '#88ff88',
    '--text-selection': '#00ff004d',
    '--text-highlight-bg': '#00640080',
    '--interactive-normal': '#1c1c1c',
    '--interactive-hover': '#2c2c2c',
    '--interactive-accent': '#008a00',
    '--interactive-accent-hover': '#00ff00',
    '--interactive-success': '#28a745',
    '--interactive-error': '#dc3545',
    '--interactive-warning': '#ffc107',
    '--titlebar-background': '#000000',
    '--titlebar-background-focused': '#000000',
    '--titlebar-text-color': '#f0f0f0',
    '--sidebar-background': '#000000',
    '--sidebar-border-color': '#002a00',
    '--header-background': '#050505',
    '--header-border-color': '#223322',
    '--vault-name-color': '#00ff00',
    '--scrollbar-thumb-bg': '#222222',
    '--scrollbar-bg': '#000000',
    '--divider-color': '#223322',
    '--checklist-done-color': '#00ff00',
    '--graph-line': '#000000',
    '--graph-node': '#00ff00',
    '--graph-text': '#ffffff',
    '--graph-node-unresolved': '#00ff00',
    '--graph-node-focused': '#000000',
    '--graph-node-tag': '#000000',
    '--graph-node-attachment': '#54ee20',
    '--blockquote-color': '#54ee20',
    '--tag-color': '#0bd62d',
  },
  themeType: 'dark',
  snippets: [],
  convertImagesToJpg: false,
  jpgQuality: 85,
};

const CITRUS_ZEST_PROFILE = {
  vars: {
    '--iconize-icon-color': '#FF8C00',
    '--background-primary': '#F5F5F5',
    '--background-primary-alt': '#f2eded',
    '--background-secondary': '#f2eded',
    '--background-secondary-alt': '#F0F0F0',
    '--background-modifier-border': '#E0E0E0',
    '--background-modifier-border-hover': '#FF8C00',
    '--background-modifier-border-focus': '#F57C00',
    '--background-modifier-flair': '#FFFFFF',
    '--background-modifier-hover': '#EEEEEE',
    '--background-modifier-active': '#E0E0E0',
    '--text-normal': '#3c3434',
    '--text-muted': '#ff7300',
    '--text-faint': '#ff7b00',
    '--text-on-accent': '#FFFFFF',
    '--text-accent': '#F57C00',
    '--text-accent-hover': '#FF9800',
    '--text-selection': '#f27602',
    '--text-highlight-bg': '#E0E0E0',
    '--cm-notice-text-default': '#e0e0e0',
    '--cm-notice-bg-default': '#f27602',
    '--interactive-normal': '#F5F5F5',
    '--interactive-hover': '#EEEEEE',
    '--interactive-accent': '#FF8C00',
    '--interactive-accent-hover': '#FFA726',
    '--interactive-success': '#4CAF50',
    '--interactive-error': '#F44336',
    '--interactive-warning': '#FFC107',
    '--titlebar-background': '#FFFFFF',
    '--titlebar-background-focused': '#F7F7F7',
    '--titlebar-text-color': '#e0e0e0',
    '--sidebar-background': '#FFFFFF',
    '--sidebar-border-color': '#E0E0E0',
    '--header-background': '#FDFDFD',
    '--header-border-color': '#E0E0E0',
    '--vault-name-color': '#F57C00',
    '--scrollbar-thumb-bg': '#BDBDBD',
    '--scrollbar-bg': '#F5F5F5',
    '--divider-color': '#E0E0E0',
    '--checklist-done-color': '#757575',
    '--graph-line': '#F57C00',
    '--graph-node': '#999999',
    '--graph-text': '#e0e0e0',
    '--graph-node-unresolved': '#F57C00',
    '--graph-node-focused': '#ffffff',
    '--graph-node-tag': '#F57C00',
    '--graph-node-attachment': '#F57C00',
  },
  themeType: 'light',
  snippets: [],
  convertImagesToJpg: false,
  jpgQuality: 85,
};

export const BUILT_IN_PROFILES_VARS = {
  Default: DEFAULT_PROFILE.vars,
  'OLED Matrix': OLED_MATRIX_PROFILE.vars,
  'Citrus Zest': CITRUS_ZEST_PROFILE.vars,
};

export const BUILT_IN_PROFILES_DATA = {
  Default: DEFAULT_PROFILE,
  'OLED Matrix': OLED_MATRIX_PROFILE,
  'Citrus Zest': CITRUS_ZEST_PROFILE,
};

export const DEFAULT_SETTINGS: PluginSettings = {
  advancedResetOptions: {
    deleteProfiles: false,
    deleteSnippets: false,
    deleteBackgrounds: false,
    deleteSettings: false,
  },
  pluginEnabled: true,
  language: 'auto',
  useRtlLayout: true,
  overrideIconizeColors: true,
  cleanupInterval: 5,
  colorUpdateFPS: 10,
  activeProfile: 'Default',
  profiles: JSON.parse(JSON.stringify(BUILT_IN_PROFILES_DATA)),
  globalSnippets: [],
  pinnedSnapshots: {},
};

export const RGB_TRIPLET_VARS = new Set([
  '--callout-default',
  '--callout-info',
  '--callout-warning',
  '--callout-error',
  '--callout-success',
  '--callout-tip',
  '--callout-question',
  '--callout-important',
  '--callout-bug',
  '--callout-example',
  '--callout-quote',
  '--callout-todo',
  '--callout-summary',
  '--callout-fail',
]);

// Maps text color variables to their common backgrounds for contrast checking.
export const TEXT_TO_BG_MAP = {
  '--text-normal': '--background-primary',
  '--text-muted': '--background-primary',
  '--text-faint': '--background-primary',
  '--text-accent': '--background-primary',
  '--text-accent-hover': '--background-primary',
  '--h1-color': '--background-primary',
  '--h2-color': '--background-primary',
  '--h3-color': '--background-primary',
  '--h4-color': '--background-primary',
  '--h5-color': '--background-primary',
  '--h6-color': '--background-primary',
  '--blockquote-color': '--background-primary',
  '--text-on-accent': '--interactive-accent',
  '--vault-name-color': '--sidebar-background',
  '--tab-text-color': '--tab-background-active',
  '--tab-text-color-active': '--tab-background-active',
  '--titlebar-text-color': '--titlebar-background',
  '--graph-text': '--graph-node',
  '--checklist-done-color': '--background-primary',
  '--text-highlight-bg': '--text-normal',
  '--tag-color': '--tag-bg',
  '--nav-item-color': '--sidebar-background',
  '--nav-item-color-hover': '--sidebar-background',
  '--nav-item-color-active': '--sidebar-background',
  '--link-color': '--background-primary',
  '--link-color-hover': '--background-primary',
  '--link-external-color': '--background-primary',
  '--link-external-color-hover': '--background-primary',
  '--link-unresolved-color': '--background-primary',
  '--caret-color': '--background-primary',
  '--code-comment': '--code-background',
  '--code-function': '--code-background',
  '--code-keyword': '--code-background',
  '--code-operator': '--code-background',
  '--code-property': '--code-background',
  '--code-string': '--code-background',
  // "--iconize-icon-color": "--background-secondary",
  // "--cm-notice-text-default": "--cm-notice-bg-default",
};
